In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv('Data Penjualan Ayam.csv')
data.head()

id         tgl  bulan  tahun  ...  bayaran supir  plat_mobil  ket
0   1  2021-01-17      1   2021  ...  1514744   NaN         NaN    2
1   2  2018-06-15      6   2018  ...  1874544   NaN         NaN    1
2   3  2020-02-17      2   2020  ...  2552796   NaN         NaN    1
3   4  2020-04-09      4   2020  ...   772080   NaN         NaN    2
4   5  2019-07-06      7   2019  ...  2096248   NaN         NaN    2

[5 rows x 16 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 221 entries, 0 to 220
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   id                221 non-null    int64  
 1   tgl               221 non-null    object 
 2   bulan             221 non-null    int64  
 3   tahun             221 non-null    int64  
 4   username          221 non-null    object 
 5   nama_perusahaan   221 non-null    object 
 6   jumlah_ayam       221 non-null    float64
 7   kg                221 non-null    float64
 8   harga_unit        221 non-null    float64
 9   total_harga       221 non-null    float64
 10  biaya_oprasional  221 non-null    int64  
 11  jumlah_mati       221 non-null    int64  
 12  bayaran           221 non-null    int64  
 13  supir             0 non-null      float64
 14  plat_mobil        0 non-null      float64
 15  ket               221 non-null    int64  
 16  year              221 non-null    int64  
dt

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [ ]:
data['year']=le.fit_transform(data['tahun'])
data.head(10)

id         tgl  bulan  tahun  ... supir plat_mobil  ket  year
0   1  2021-01-17      1   2021  ...   NaN        NaN    2     3
1   2  2018-06-15      6   2018  ...   NaN        NaN    1     0
2   3  2020-02-17      2   2020  ...   NaN        NaN    1     2
3   4  2020-04-09      4   2020  ...   NaN        NaN    2     2
4   5  2019-07-06      7   2019  ...   NaN        NaN    2     1
5   6  2020-06-03      6   2020  ...   NaN        NaN    2     2
6   7  2019-12-15     12   2019  ...   NaN        NaN    2     1
7   8  2020-09-11      9   2020  ...   NaN        NaN    2     2
8   9  2020-01-02      1   2020  ...   NaN        NaN    2     2
9  10  2018-04-17      4   2018  ...   NaN        NaN    1     0

[10 rows x 17 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
data['jumlah_ayam']=scaler.fit_transform(data[['jumlah_ayam']])
data['harga_unit']=scaler.fit_transform(data[['harga_unit']])
data['total_harga']=scaler.fit_transform(data[['total_harga']])
data.head(10)

id         tgl  bulan  tahun  ... supir plat_mobil  ket  year
0   1  2021-01-17      1   2021  ...   NaN        NaN    2     3
1   2  2018-06-15      6   2018  ...   NaN        NaN    1     0
2   3  2020-02-17      2   2020  ...   NaN        NaN    1     2
3   4  2020-04-09      4   2020  ...   NaN        NaN    2     2
4   5  2019-07-06      7   2019  ...   NaN        NaN    2     1
5   6  2020-06-03      6   2020  ...   NaN        NaN    2     2
6   7  2019-12-15     12   2019  ...   NaN        NaN    2     1
7   8  2020-09-11      9   2020  ...   NaN        NaN    2     2
8   9  2020-01-02      1   2020  ...   NaN        NaN    2     2
9  10  2018-04-17      4   2018  ...   NaN        NaN    1     0

[10 rows x 17 columns]

In [ ]:
databaru=data[['year','jumlah_ayam','harga_unit','total_harga']]
databaru.head()

year  jumlah_ayam  harga_unit  total_harga
0     3    -0.459818    1.135237    -0.018756
1     0    -0.252249    1.564848     0.363654
2     2     1.645524    0.031173     1.543683
3     2    -1.616273    0.842155    -1.310850
4     1     0.370458    1.411936     0.992950

In [ ]:
x = databaru[['year','harga_unit','total_harga']]
y = databaru[['jumlah_ayam']].values

In [ ]:
x

year  harga_unit  total_harga
0       3    1.135237    -0.018756
1       0    1.564848     0.363654
2       2    0.031173     1.543683
3       2    0.842155    -1.310850
4       1    1.411936     0.992950
..    ...         ...          ...
216     2   -1.674984     0.549711
217     3    0.598223    -0.412663
218     0    0.704716     0.611232
219     2   -0.011606     0.018309
220     0    1.488847     1.588744

[221 rows x 3 columns]

In [ ]:
y

array([[-0.45981813],
       [-0.25224922],
       [ 1.64552365],
       [-1.61627347],
       [ 0.3704575 ],
       [-0.84530324],
       [-0.72669244],
       [-1.55696807],
       [-0.75634514],
       [-1.08252485],
       [ 0.2518467 ],
       [-0.90460865],
       [ 0.07393049],
       [-0.96391405],
       [-0.40051273],
       [-1.37905187],
       [ 0.96351152],
       [-0.99356675],
       [-0.31155462],
       [ 1.70482905],
       [-1.55696807],
       [-1.23078836],
       [-1.49766267],
       [-0.34120733],
       [ 1.20073313],
       [-1.64592618],
       [-1.52731537],
       [ 0.2518467 ],
       [ 0.07393049],
       [-0.63773434],
       [ 0.60767911],
       [-1.11217755],
       [ 1.28969124],
       [-0.78599784],
       [-1.34939916],
       [-1.17148296],
       [-0.31155462],
       [-0.63773434],
       [ 0.84490072],
       [ 0.60767911],
       [-0.84530324],
       [-0.22259652],
       [ 0.54837371],
       [ 1.20073313],
       [-1.14183026],
       [-0

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=4)

In [ ]:
X_train.shape

(176, 3)

In [ ]:
X_test.shape

(45, 3)

In [ ]:
from sklearn import linear_model
regr = linear_model.LinearRegression()

In [ ]:
regr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
regr.predict(X_test)

array([[ 0.17776378],
       [-0.4973598 ],
       [ 0.7936531 ],
       [-1.40669672],
       [ 0.68200725],
       [ 0.02183179],
       [ 1.28046991],
       [-1.53111994],
       [ 0.61383825],
       [ 0.96152633],
       [-0.39528791],
       [-0.77967709],
       [ 1.59909634],
       [-0.57664465],
       [-0.82910073],
       [ 1.24315031],
       [ 1.84251868],
       [-0.32746588],
       [-0.29028333],
       [ 1.05719442],
       [-0.84785249],
       [ 1.97439703],
       [-0.83348243],
       [-1.12637333],
       [ 0.83819237],
       [-0.37583764],
       [ 0.69659212],
       [-0.27908721],
       [-0.37006673],
       [-1.71786329],
       [-1.45931248],
       [-1.67578205],
       [ 0.77807537],
       [ 0.29659901],
       [ 1.47835679],
       [ 0.38218089],
       [-0.94738201],
       [-0.12544627],
       [-1.4792995 ],
       [ 1.11507901],
       [ 0.07305101],
       [ 1.29395924],
       [-0.36540037],
       [ 1.3518999 ],
       [ 0.62742089]])

In [ ]:
ypred = regr.predict(X_test)
ypred

array([[ 0.17776378],
       [-0.4973598 ],
       [ 0.7936531 ],
       [-1.40669672],
       [ 0.68200725],
       [ 0.02183179],
       [ 1.28046991],
       [-1.53111994],
       [ 0.61383825],
       [ 0.96152633],
       [-0.39528791],
       [-0.77967709],
       [ 1.59909634],
       [-0.57664465],
       [-0.82910073],
       [ 1.24315031],
       [ 1.84251868],
       [-0.32746588],
       [-0.29028333],
       [ 1.05719442],
       [-0.84785249],
       [ 1.97439703],
       [-0.83348243],
       [-1.12637333],
       [ 0.83819237],
       [-0.37583764],
       [ 0.69659212],
       [-0.27908721],
       [-0.37006673],
       [-1.71786329],
       [-1.45931248],
       [-1.67578205],
       [ 0.77807537],
       [ 0.29659901],
       [ 1.47835679],
       [ 0.38218089],
       [-0.94738201],
       [-0.12544627],
       [-1.4792995 ],
       [ 1.11507901],
       [ 0.07305101],
       [ 1.29395924],
       [-0.36540037],
       [ 1.3518999 ],
       [ 0.62742089]])

In [ ]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

print("r1 score : ", r2_score(y_test, ypred))
print("MAE score: ", mean_absolute_error(y_test, ypred))
print("MSE score: ", mean_squared_error(y_test, ypred))

r1 score :  0.9782037234721139
MAE score:  0.11513657891876995
MSE score:  0.023213569153688888


In [ ]:
print ('Coefficients (b) : ', regr.coef_)
print ('Intercept (a) : ', regr.intercept_)

Coefficients (b) :  [[ 0.0243601  -0.42489878  1.05400112]]
Intercept (a) :  [-0.04585535]
